# Generated by Django 4.2.6 on 2025-03-06 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstAidModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(max_length=100, verbose_name='Catégorie')),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Débutant'), (2, 'Intermédiaire'), (3, 'Avancé')], default=1, verbose_name='Niveau de difficulté')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Module de premiers secours',
                'verbose_name_plural': 'Modules de premiers secours',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('passing_score', models.IntegerField(default=70, verbose_name='Score de passage (%)')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='premiers_secours.firstaidmodule')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField(verbose_name='Question')),
                ('order', models.IntegerField(default=0, verbose_name='Ordre')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='premiers_secours.quiz')),
            ],
            options={
                'verbose_name': 'Question de quiz',
                'verbose_name_plural': 'Questions de quiz',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_text', models.CharField(max_length=255, verbose_name='Option')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Est correcte')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='premiers_secours.quizquestion')),
            ],
            options={
                'verbose_name': 'Option de réponse',
                'verbose_name_plural': 'Options de réponse',
            },
        ),
        migrations.CreateModel(
            name='FirstAidContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content_type', models.CharField(choices=[('video', 'Vidéo'), ('image', 'Image'), ('audio', 'Audio'), ('text', 'Texte'), ('checklist', 'Checklist')], max_length=10, verbose_name='Type de contenu')),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('file', models.FileField(blank=True, null=True, upload_to='first_aid_content/', verbose_name='Fichier')),
                ('file_size', models.IntegerField(default=0, verbose_name='Taille (Ko)')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='premiers_secours.firstaidmodule')),
            ],
            options={
                'verbose_name': 'Contenu de premiers secours',
                'verbose_name_plural': 'Contenus de premiers secours',
                'ordering': ['module', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserQuizResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(verbose_name='Score obtenu')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('passed', models.BooleanField(default=False, verbose_name='Réussi')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_results', to='premiers_secours.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Résultat de quiz',
                'verbose_name_plural': 'Résultats de quiz',
                'unique_together': {('user', 'quiz')},
            },
        ),
    ]
